#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
[ -f ~/.alias ] && source ~/.alias
[ -f ~/.functions ] && source ~/.functions

# Smart change directory (cd)
setopt autocd
#unsetopt correct_all
unsetopt correct
cdpath=($HOME/code/scripts $HOME/code $HOME/tickets $HOME)

# History management
export HISTSIZE=100000
export HISTFILESIZE=100000000
export HISTCONTROL=erasedups

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/own/forgit/forgit.plugin.zsh ] && source ~/own/forgit/forgit.plugin.zsh
[ -f ~/own/enhancd/init.sh ] && export ENHANCD_DISABLE_DOT=1 && export ENHANCD_DISABLE_HOME=1 && ENHANCD_HYPHEN_NUM=20 && source ~/own/enhancd/init.sh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# OPENSSL Path and Compilation Flags
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl@1.1/lib/
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib $LDFLAGS"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include $CPPFLAGS"
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig:$PKG_CONFIG_PATH"

# MYSQL Path and Compilation Flags
# Compilation flags with mysql-client
# export PATH="/usr/local/opt/mysql-client/bin:$PATH"
# export LDFLAGS="-L/usr/local/opt/mysql-client/lib $LDFLAGS"
# export CPPFLAGS="-I/usr/local/opt/mysql-client/include $CPPFLAGS"
# export PKG_CONFIG_PATH="/usr/local/opt/mysql-client/lib/pkgconfig:$PKG_CONFIG_PATH"
# export PYCURL_SSL_LIBRARY=openssl CFLAGS="-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib"

# FZF
# This makes fzf use rg to list the files when calling it without parameters (which is faster than letting fzf search files by itself)
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export H=$HOME

# Java Environment
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

# Python Environment
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export PATH="$HOME/.pyenv/bin:$PATH"

# PIP on environments: at the moment, I'm just creating a pip.conf file in each environment folder.
# But, if at some point a single configuration is enough, we can use this variable (PIP_INDEX_URL)
#export PIP_INDEX_URL=https://dany.farina@glovoapp.com:AKCp5emFpvHGSweH4VTvzS5Sfa2gmxy7eDUqoaQDoUfeDx94tGMJa6PGVZ9nnS251z6eXQvqJ@artifactory.glovoint.com/artifactory/api/pypi/glovo-pypi/simple
export PATH="/usr/local/opt/mysql-client/bin:$PATH"
export PATH="$HOME/code/scripts:$PATH"
  
# Manage Node.js versions using nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
